# Go cross compiler (xgo): Go 1.13.x
# Copyright (c) 2019 Péter Szilágyi. All rights reserved.
#
# Released under the MIT license.

FROM chrisfranko/xgo-1.13.4

MAINTAINER Christopher Franko <chrisjfranko@gmail.com>
