# Go cross compiler (xgo): Wildcard layer to the latest 1.4 release
# Copyright (c) 2014 Péter Szilágyi / 2021 Christopher Franko. All rights reserved.
#
# Released under the MIT license.

FROM chrisfranko/xgo-1.4.2

MAINTAINER Christopher Franko <chrisjfranko@gmail.com>
