# Go cross compiler (xgo): Wildcard layer to the latest Go release
# Copyright (c) 2017 Péter Szilágyi. All rights reserved.
#
# Released under the MIT license.

FROM chrisfranko/xgo-1.17.x

MAINTAINER Christopher Franko <chrisjfranko@gmail.com>
