# Go cross compiler (xgo): Go 1.10.x
# Copyright (c) 2018 Péter Szilágyi. All rights reserved.
#
# Released under the MIT license.

FROM chrisfranko/xgo-1.10.4

MAINTAINER Christopher Franko <chrisjfranko@gmail.com>
