# Go cross compiler (xgo): Go 1.12.x
# Copyright (c) 2019 Péter Szilágyi. All rights reserved.
#
# Released under the MIT license.

FROM chrisfranko/xgo-1.12.13

MAINTAINER Christopher Franko <chrisjfranko@gmail.com>
