# Go cross compiler (xgo): Wildcard layer to the latest 1.9 release
# Copyright (c) 2017 Péter Szilágyi. All rights reserved.
#
# Released under the MIT license.

FROM chrisfranko/xgo-1.9.4

MAINTAINER Christopher Franko <chrisjfranko@gmail.com>
